### gGET all players
GET http://localhost:3000/players

### GET a specific player based on his playerId
GET http://localhost:3000/players/231747

### Create a player
POST http://localhost:3000/players
Content-Type: application/json

{
        "playerId" : "1234",
        "name" : "test",
        "nationality" : "testNatio",
        "club" : "testytest",
        "overallRating" : "123"
}

### DELETE a specific player based on his playerId
DELETE http://localhost:3000/players/1234


### Update a specific player based on his playerId
PATCH http://localhost:3000/players/1234
Content-Type: application/json

 {
    "name" : "newName!"
 }
